extract_patches: change the default layout of output directories
Previously, it extracts the patches in the git repository pathes.
but it's obscure, so this changes the default path as same as
the projects pathes.

P.S. To use the previous way, please add the option of '--REPOPATH'.

Signed-off-by: Horace Hsieh <xiehong@marvell.com>

diff --git a/tools/extract_patches b/tools/extract_patches
--- a/tools/extract_patches
+++ b/tools/extract_patches
@@ -1,11 +1,14 @@
 #!/bin/sh
 
 print_usage() {
-    echo "Usage: extract_patches <output> <changelog> [-e exclude list ]"
+    echo "Usage: extract_patches <output> <changelog> [-e LIST ] [--REPOPATH]"
+    echo "-e LIST, the excluded list seperated by blank"
+    echo "--REPOPATH, extract patches into git repository pathes,"
+    echo "            instead of project pathes"
     echo "Please run me in the root directory of android source code.    "
 }
 
-if [ $# -lt 2 ] || [ ! -f $2 ] || [ $# -gt 2 -a "$3" != "-e" ]; then
+if [ $# -lt 2 ] || [ ! -f $2 ] || ([ $# -gt 2 ] && [ "$3" != "-e" -a "$3" != "--REPOPATH" ]); then
     print_usage
     exit 1
 fi
@@ -13,21 +16,27 @@ fi
 OUTPUT=$1
 CHGLOG=$2
 shift 2
-if [ $# -gt 0 ]; then
-    shift
-fi
+excluded=0
+repo_path=0
+top_dir=`pwd`
 
 while [ $# -gt 0 ]
 do
-    if [ $# -eq 1 ]; then
-	exclude_prjs=$1
-    else
-	exclude_prjs=$exclude_prjs" "$1
+    if [ $1 = "--REPOPATH" ]; then
+        repo_path=1
+    elif [ $1 = "-e" ]; then
+        excluded=1
+    elif [ $excluded = 1 ]; then
+        if [ -z "$excluded_prjs" ]; then
+	    excluded_prjs=$1
+        else
+	    excluded_prjs=$excluded_prjs" "$1
+        fi
     fi
     shift
 done
 
-patches=$(awk -v elist="$exclude_prjs" -F[ ' \
+patches=$(awk -v elist="$excluded_prjs" -F[ ' \
          BEGIN  {  split(elist, excluded, " ") } \
          /prj:/ {  ignored=0; \
                    gpath=$1; \
@@ -54,16 +63,25 @@ for p in $patches
 do
     prj=`echo $p | awk -F: '{ print $1 }'`
     if [ "$prj" != "$prev_prj" ]; then
-	prev_prj=$prj
-	num=1
-	path=`repo forall $prj -c 'echo $(pwd)'`
-	if [ -z "$path" ]; then
-	    echo "Invalid project: $prj."
-	    continue;
-	fi
-	mkdir -p $OUTPUT/$prj
-	cd $path;
+        if [ -n "$prev_prj" ]; then
+            prev_prj=
+        fi
+        cd $top_dir
+        num=1
+        path=`repo list $prj | awk -F: '{ print $1 }'`
+        if [ -z "$path" ]; then
+            echo "Invalid project: $prj."
+            continue;
+        fi
+        prev_prj=$prj
+        if [ $repo_path = 0 ]; then
+            PRJ_OUTPUT=$OUTPUT/$path
+        else
+            PRJ_OUTPUT=$OUTPUT/$prj
+        fi
+	mkdir -p $PRJ_OUTPUT
+	cd $path #dash doesn't support pushd/popd
     fi
-    echo $p | awk -F: '{ print $2 }' | xargs git format-patch -o $OUTPUT/$prj -1 --start-number $num
+    echo $p | awk -F: '{ print $2 }' | xargs git format-patch -o $PRJ_OUTPUT -1 --start-number $num
     num=$((num+1))
 done
